### ISSUE TITLE
Failing Travis build on CNOT(q1,q2)

### ISSUE THREAD

**Issue by caryan** [BBN-Q/QGL#1]
The [latest Travis build](https://travis-ci.org/BBN-Q/QGL/builds/103961167) is failing because the `q1q2` channel is shorter than the `q1` and `q2` channels.  This is because `q1` and `q2`'s physical channels are [initialized to 1.2Gs/s](https://github.com/BBN-Q/QGL/blob/bda2a703b7b1019414248ccfe3701cebd9960607/tests/test_QGL.py#L136).  However `q1q2` is not setup  and so [defaults to 1GS/s](https://github.com/BBN-Q/QGL/commit/7317020dff379212f702d23de3fd15a7bbd74d21). A possible solution is to just leave q1 and q2 at 1GS/s.

@blakejohnson I imagine this works locally for you because you have a `q1q2` channel in your ChannelLibrary with a 1.2GS/s sampling rate.

**Comment by blakejohnson** [comment]
Fixed in 17e36c9bc0d0285e98d22285714bed2df7fb2e37.
