### ISSUE TITLE
add ability to associate a destination address with a measurement

### ISSUE THREAD

**Issue by dellard** [BBN-Q/QGL#142]
Hardware under development will permit measurements annotated with the memory addresses to which the measured runtime-values are stored, i.e.

```Python
    MEASA(q1, 44)  # measure q1; put the value into address 44
```

(for reasons having to do with the way Pulses are compiled, it's more convenient at this time to create a new method to create these "annotated measurements" rather than just adding another kwarg to `MEAS`, although this might be revisited in the future.  If, in the future, all measurements are annotated, then we won't need to distinguish them.)

**Comment by dieris** [comment]
Closed by https://github.com/BBN-Q/QGL/pull/168
