### ISSUE TITLE
Gate markers on shared channels

### ISSUE THREAD

**Issue by jaseung** [BBN-Q/QGL#162]
I found that two-qubit RB sequence created by QGL is not right. Shown below is the 4 Clifford gates for two qubit RB, measured with our oscilloscope. The pulse sequence plot in the jupyter notebook looks the same as in the oscilloscrope, so I thought this would be a QGL issue.

The problem is that the qubit pulse train appears to go out of sync with the gate pulses so a gap appears between the ends of gate and qubit pulse train. 

Can you see if this is reproducible in your QGL and if yes, would you fix it?

![image](https://user-images.githubusercontent.com/22563147/39268453-079b7c42-489e-11e8-99b3-8d970e4361bf.png)

**Comment by dieris** [comment]
@jaseung please try https://github.com/BBN-Q/QGL/pull/163

**Comment by dieris** [comment]
I actually can't reproduce this issue anymore after the fix above. Can you try to set all delays to 0 and see where your markers go out of sync? Is it at a specific point in the sequence, or is it cumulative?

**Comment by jaseung** [comment]
Hmm, it's the same. I set all delays to 0 and still see the same problems (gate and qubit out of sync). I even tried with markers disabled, but no luck. To see if there is any difference, I also tried to use QGL-last-matlab release, but the result is the same. Which QGL version did you use to test the fix? Any suggestion?

Just in case you're interested, I attached the ChannelParams.json below.

*ChannelParams.zip
[ChannelParams.zip](https://github.com/BBN-Q/QGL/files/1961620/ChannelParams.zip)

*Screencapture of pulse trains in jupyter-notebook.
![twoq_rb_pulse_issue3](https://user-images.githubusercontent.com/22563147/39441747-ec6acd96-4c7c-11e8-80e1-9d1884a78f60.PNG)

**Comment by dieris** [comment]
I'm only testing on the master branch. Unfortunately we do not support the matlab-compatible version anymore. It seems that your settings are alright, though. What happens when you disable the `gatechan` for both `q2` and `CR12`?

**Comment by jaseung** [comment]
With gate channels for q2 and CR12, there's still the same issue. Well, I
guess I should try the master branch.  Can you provide a measure.yml for me
to use in QGL to create two-qubit RB?

Jaseung

**Comment by jaseung** [comment]
Sorry, I meant ' With gate channels for q2 and CR12 disabled'.

Jaseung

**Comment by dieris** [comment]
Sent by email

**Comment by dieris** [comment]
Remaining issue, reported by @jaseung : control qubit gate (marker) stays high when combined with a gate on the CR pulse in the same channel
