### ISSUE TITLE
APS2 firmware v4 support

### ISSUE THREAD

**Issue by caryan** [BBN-Q/QGL#22]
APS2 v4 firmware has new features we should support in the translator

- [x] deep waveform memory with prefetching
- [x] SSB modulation (need to invert sign)
- [x] frame changes
- [x] waveform engine select (broadcasting only for now)
- [x] instruction prefetching

**Comment by blakejohnson** [comment]
Close?

**Comment by caryan** [comment]
Looks like everything is checked.
