### ISSUE TITLE
Update example notebooks

### ISSUE THREAD

**Issue by ahelsing** [BBN-Q/QGL#224]
Update the example QGL notebooks, to reflect using Auspex and other recent changes.
Where appropriate, reference Auspex notebooks for detailed examples.
Include some text indicating what order to go through the example notebooks.

**Comment by ahelsing** [comment]
Add a sample saved DB under doc for use with the sample QGL notebooks. Auspex can have its own sample saved DB.

**Comment by dieris** [comment]
Closed by https://github.com/BBN-Q/QGL/pull/226
