### ISSUE TITLE
Have `compile_to_hardware` save the "code" it is compiling.

### ISSUE THREAD

**Issue by blakejohnson** [BBN-Q/QGL#43]

**Comment by blakejohnson** [comment]
So, to do this, we don't even need the `meta` package, we just need to effectively to do:
```python
fid = open("output.txt", "w")
fid.write(str(seqs))
fid.close()
```
This would be a good first step, but it is not exactly human readable. Do we care?

If we do want it to be human readable, then I would propose saving a copy of the channel dictionaries, and then expanding the `Pulse` pretty printers so that they output just enough information to reproduce the object when reconstructed from their `str` representation.

**Comment by caryan** [comment]
Since this will mainly be for experiment archaeology or debugging purposes, human readable seem desirable.
