### ISSUE TITLE
Unicode character 'circled times'

### ISSUE THREAD

**Issue by dieris** [BBN-Q/QGL#51]
Getting this error in [save_code](\https://github.com/BBN-Q/QGL/blob/7316bcb389dee1873b3cb19c56e4b23d7af18c35/QGL/Compiler.py#L645) for any sequence with a tensor product. 

`UnicodeEncodeError: 'charmap' codec can't encode character u'\u2297' in position 7: character maps to <undefined>`

**Comment by caryan** [comment]
Hmmm, must be a Windows only issue.

**Comment by dieris** [comment]
both Win 8 and 10

**Comment by caryan** [comment]
@dieris  could you give this branch a try: 99b90368bb7f9f89554ed71fbb180e89688e8b63

**Comment by dieris** [comment]
Closed by https://github.com/BBN-Q/QGL/commit/45226f717e27ef3dc7f0ff765c8f074c0c8ab382
