### ISSUE TITLE
Slow build up of Pulse representation

### ISSUE THREAD

**Issue by dieris** [BBN-Q/QGL#53]
These two [for loops] (\https://github.com/BBN-Q/QGL/blob/45226f717e27ef3dc7f0ff765c8f074c0c8ab382/QGL/PulseSequencer.py#L85-L93) severely slow down compile time of long sequences (e.g. seconds to tens of minutes for GST)

**Comment by caryan** [comment]
This, and many of our other performance issues, would probably be helped by reactivating `Pulse` caching.

**Comment by caryan** [comment]
@dieris out of curiosity how big are the `-code.py` files?

**Comment by dieris** [comment]
400 kB at most

**Comment by blakejohnson** [comment]
@caryan why would caching pulses help with "string-ifying" code? I guess we could also cache the string representation...

**Comment by dieris** [comment]
Closed by https://github.com/BBN-Q/QGL/pull/60
