### ISSUE TITLE
PulseSequencePlotter clobbers 'BBNAPS1' instrument translator

### ISSUE THREAD

**Issue by matthewware** [BBN-Q/QGL#7]
If you happen to have an APS2 called 'BBNAPS1' build_awg_translator_map() overwrites the translator with APSPattern.  Is there a reason translators has to contain 'APS1' and 'BBNAPS1' and explicitly write their translators?
https://github.com/BBN-Q/QGL/blob/master/QGL/PulseSequencePlotter.py#L52

**Comment by blakejohnson** [comment]
No, that was just some test code that I forgot to delete. Good catch.
